name: wallkick-play-system
version: '1.0'
main: jp.furaito.baito.wallkickPlaySystem.WallkickPlaySystem
api-version: '1.21'
depend: [WorldEdit]

commands:
  wallkickplaysettings:
    description: "Wallkick Playing initialize Settings."
    permission: op
    permission-message: "Only players with op. Not console. Not command_block."
    aliases: [wkps]